[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arya Gupta", email = "aryagupta164@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncmy>=0.2.13",
    "fastapi>=0.141.1",
    "pwdlib>=0.3.0",
    "pydantic-settings>=2.15.0",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.2",
    "python-jose>=3.5.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
